#
# Prevent displaying inside an iframe
#
add_header 'X-Frame-Options' 'SAMEORIGIN';
add_header 'Content-Security-Policy' "frame-ancestors 'self' https://*.atheer.dev https://*.atheer.si https://*.atheer.qa https://*.atheer.io";
